# Generated by Django 4.2.7 on 2023-11-19 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='reg_data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 11, 19, 17, 4, 11, 195383, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 19, 17, 4, 20, 81770, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
