# Generated by Django 4.2.7 on 2023-11-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormHandler', '0002_user_data_reg_data_user_data_reg_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('reg_data', models.DateField(auto_now_add=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('agreement_check', models.BooleanField()),
            ],
        ),
    ]
